// Author + freshness signals: one model for the byline, the visible "Updated"
// stamp, and the JSON-LD dateModified they must agree with.
//
// WHAT WAS ACTUALLY THERE, measured 2026-08-09 before writing any of this:
//   - guides had NO byline component and NO visible Updated stamp. The only
//     visible "Christopher Myers" was the signature in the closing CTA, which
//     is a sign-off, not an author credit.
//   - every one of the 14 guides carried the SAME hardcoded
//     "dateModified": "2026-07-29" — not sourced from anything, and stale
//     against a git history that had moved twice since.
//   - blog posts ALREADY had a byline row and already derived the visible
//     stamp, the JSON-LD date and the sitemap lastmod from one function
//     (modifiedOf in build-blog.mjs). That half needed a link, not a rebuild.
//
// THE DATE SOURCE IS src/data/page-dates.json — git last-commit date per
// route, generated by `npm run seo:dates` and held current by dates:check.
// Using it rather than re-shelling to git means the guides' freshness claim
// and the sitemap's <lastmod> are the same number by construction, and it
// keeps working on Cloudflare's shallow clone where per-file git log does not.
//
// "Never show a fresher date without a content change" is therefore satisfied
// structurally: the date only moves when the file's last commit moves.
import fs from "node:fs";
import path from "node:path";
import { COMPANY, ROOT } from "./config.mjs";

const MONTHS = [
	"January", "February", "March", "April", "May", "June",
	"July", "August", "September", "October", "November", "December",
];

let DATES = null;
function pageDates() {
	if (DATES) return DATES;
	try {
		DATES = JSON.parse(fs.readFileSync(path.join(ROOT, "src", "data", "page-dates.json"), "utf8"));
	} catch {
		DATES = {};
	}
	return DATES;
}

/** ISO date for a route, or null when git has never seen the file. */
export function modifiedIso(route) {
	return pageDates()[route] || null;
}

/**
 * "August 2026". MONTH GRANULARITY IS DELIBERATE. A day-level stamp on an
 * evergreen guide invites the reader to read a one-line typo fix as a revision,
 * and it churns the visible diff on every commit. The JSON-LD keeps full
 * precision because machines want it; humans get the month.
 */
export function updatedLabel(route) {
	const iso = modifiedIso(route);
	if (!iso) return null;
	const [y, m] = iso.split("-");
	return `${MONTHS[Number(m) - 1]} ${y}`;
}

/**
 * YMYL-adjacent guides: money and data-handling advice, where a reader acting
 * on a stale or unreviewed number has something real at stake. These get the
 * extra "Reviewed by" line. The list is explicit rather than keyword-matched —
 * "which of our pages carry money advice" is an editorial judgement, and a
 * regex over slugs would quietly pick up or drop one as titles change.
 */
export const YMYL_GUIDES = new Set([
	"/guides/ai-consultant-cost/",
	"/guides/what-ai-automation-costs-to-run/",
	"/guides/ai-roi-math-small-business/",
	"/guides/ai-consultant-vs-in-house/",
	"/guides/ai-data-cloud-vs-on-prem/",
	"/guides/private-ai-for-small-business/",
]);

export const AUTHOR_NAME = COMPANY.founder.name;
export const AUTHOR_ROLE = `Founder, ${COMPANY.name}`;

/**
 * The byline component. One <p>, no card, no avatar — the site has no author
 * photo idiom and inventing one for this would be a new component to maintain.
 *
 * rel="author" is on the link so the author relationship is machine-readable
 * from the markup as well as from the Person node in the graph.
 */
export function bylineHtml(route, { reviewed = false } = {}) {
	const label = updatedLabel(route);
	const parts = [
		`<a href="/about/" rel="author">${AUTHOR_NAME}</a> &mdash; ${AUTHOR_ROLE}`,
	];
	if (label) parts.push(`<span class="byline__updated">Updated ${label}</span>`);
	const line = parts.join(` <span class="byline__sep" aria-hidden="true">&middot;</span> `);
	const review =
		reviewed && label
			? `\n      <span class="byline__reviewed">Reviewed by ${AUTHOR_NAME}, ${label}</span>`
			: "";
	return `<p class="byline">${line}${review}</p>`;
}
