#!/usr/bin/env node
// Sweep every rendered page for price-like and phone-like strings that are not
// canonical. The catch-all guard behind the fact system: check-facts.mjs proves
// the STAMPED spans are right, but a number typed straight into prose, a meta
// description, or a JSON-LD offer was never stamped and so was never checked.
//
//   npm run numbers:check
//
// WHAT THIS DELIBERATELY DOES NOT DO, and why it would be useless otherwise:
// a check that failed on "any price not in site-facts.json" fires on 104
// distinct money tokens, ~95 of them legitimate — the guides' competitor-rate
// comparisons ($130,000–$200,000 for an in-house hire), the ROI calculator's
// worked examples, per-million token costs ($25.20), MARCUS proof figures.
// Failing a build on those trains people to ignore the build. Editorial market
// data is not a price claim about us.
//
// So the rules are scoped to where the site states ITS OWN facts:
//
//   1. PHONE, everywhere — strict. There is exactly one number. Anything else
//      phone-shaped fails, wherever it appears.
//   2. PRICES in fact-bearing contexts — <title>, meta descriptions, JSON-LD,
//      and data-fact spans. A price in those positions is a claim about what we
//      charge, so it must be canonical.
//   3. priceRange exactness — the JSON-LD composite, re-derived, not stored.
//   4. NEAR-MISS ranges, everywhere — a range pairing a canonical endpoint with
//      a non-canonical one ("$18,000–$45,000"). That is the half-updated-price
//      failure mode, and it is what a repricing actually leaves behind.
//   5. RETIRED tokens, everywhere — the $12,000–$45,000 band.
//
// Prose prices outside those contexts are counted and REPORTED, never failed,
// so the scope is visible rather than silent.
import fs from "node:fs";
import path from "node:path";
import { COMPANY, LOCAL_SCRATCH_DIRS, ROOT } from "./lib/config.mjs";
import { priceRange, phoneForms } from "./lib/fact-values.mjs";

let failures = 0;
let warnings = 0;
const fail = (msg) => { console.error(`  ERROR  ${msg}`); failures++; };
const warn = (msg) => { console.warn(`  WARN   ${msg}`); warnings++; };

// --- canonical vocabularies -------------------------------------------------

const usd = (n) => "$" + n.toLocaleString("en-US");
const svc = (key) => COMPANY.services.find((s) => s.key === key);

// Every price string the site is allowed to state about itself.
const CANONICAL_PRICES = new Set([
	...COMPANY.services.flatMap((s) => [
		s.price,
		usd(s.priceLow),
		s.priceHigh ? usd(s.priceHigh) : null,
	]),
	usd(svc("audit").priceLow) + "+",   // the "audit-floor" fact
	priceRange(COMPANY),                 // the JSON-LD composite
	COMPANY.runningCosts.match(/\$[\d,]+–\$[\d,]+/)?.[0], // "$50–$500"
	COMPANY.audience.revenue,            // "$1M–$50M"
].filter(Boolean));

// The individual endpoints, for near-miss range detection.
const CANONICAL_ENDPOINTS = new Set(
	COMPANY.services.flatMap((s) => [s.priceLow, s.priceHigh]).filter(Boolean),
);

const PHONE_FORMS = new Set([
	...phoneForms(COMPANY),
	COMPANY.phone.replace(/-/g, ""),        // 9283636639
	COMPANY.phoneHref.replace(/^tel:/, ""), // +19283636639
]);

// Tokens that must never appear again, with the reason shown on failure.
const RETIRED = [
	{ pattern: /\$12,000\s*[–—-]\s*\$45,000/g, why: "retired sprint band (pre-2026-07 repricing) — canonical is " + svc("sprint").price },
];

// --- patterns ---------------------------------------------------------------

// A money token must END ON A DIGIT — hence `[0-9](?:[0-9,]*[0-9])?` rather
// than `[0-9][0-9,]*`. In prose like "$18,000–$60,000, fixed" the greedy form
// swallows the sentence comma and yields "$60,000,", which matches no
// canonical value and reported a false failure on ~20 pages. A trailing
// negative lookahead does NOT fix this: it only tests what follows the match,
// while the comma has already been consumed.
const AMOUNT = "[0-9](?:[0-9,]*[0-9])?(?:\\.[0-9]+)?";
const MONEY = new RegExp(`\\$${AMOUNT}(?:\\s*[KMB]\\b)?`, "g");
const RANGE = new RegExp(`\\$(${AMOUNT})\\s*[–—-]\\s*\\$(${AMOUNT})`, "g");
// Deliberately loose: it is better to inspect a false phone match than to miss
// a real second number. 555-01xx placeholders are handled by context, below.
const PHONE = /(?:\+1[-.\s]?)?\(?[0-9]{3}\)?[-.\s][0-9]{3}[-.\s][0-9]{4}/g;

const num = (s) => Number(String(s).replace(/,/g, ""));

// --- file walk --------------------------------------------------------------

function* htmlFiles(dir) {
	for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
		if (LOCAL_SCRATCH_DIRS.has(e.name) || e.name.startsWith(".")) continue;
		const p = path.join(dir, e.name);
		if (e.isDirectory()) yield* htmlFiles(p);
		// emails/preview/ is generated by `npm run test:book` and gitignored —
		// local artifacts, not pages. Its fixtures carry deliberately fake
		// numbers ((555) 201-4400), which would fail rule 1 forever.
		else if (e.name.endsWith(".html") && !p.includes(`emails${path.sep}preview`)) yield p;
	}
}

const lineOf = (text, index) => text.slice(0, index).split("\n").length;

// Strip what is not a claim: CSS (a comment in a <style> block mentioning
// "$45,000" for layout notes is not a price), HTML comments, and non-JSON-LD
// scripts. JSON-LD is KEPT — it is the most fact-bearing region on the page.
function stripNonClaims(html) {
	const blank = (m) => m.replace(/[^\n]/g, " "); // preserve line numbers
	return html
		.replace(/<style[\s\S]*?<\/style>/gi, blank)
		.replace(/<!--[\s\S]*?-->/g, blank)
		.replace(/<script(?![^>]*ld\+json)[\s\S]*?<\/script>/gi, blank);
}

// The regions where a price is a STRUCTURED claim about what we charge.
//
// Narrower than "meta tags and JSON-LD", and the first cut got this wrong.
// A meta description and a FAQPage `acceptedAnswer.text` are PROSE that
// happens to sit in the head — /guides/chatgpt-vs-custom-ai/ legitimately
// describes ChatGPT's own "$20–$30/month" there, and the guides' FAQ answers
// quote competitor rates. Failing those said "your meta description is lying
// about your pricing" about an accurate sentence describing someone else's.
//
// So only machine-readable price FIELDS are held to canonical values. Prose
// everywhere — body, meta, FAQ answers — is covered instead by the near-miss
// and retired-token rules, which catch the failure that actually happens:
// a repricing that updated some copies and not others.
function factBearingRegions(html) {
	const out = [];
	const push = (label, re) => {
		for (const m of html.matchAll(re)) {
			// First non-undefined group: the alternation below captures a quoted
			// value in group 1 and a bare number in group 2.
			const text = m.slice(1).find((g) => g !== undefined) ?? "";
			out.push({ label, text, index: m.index });
		}
	};
	// schema.org price fields, inside any ld+json block. The value alternation
	// is load-bearing: a naive `"?([^",}]*)"?` stops at the comma INSIDE
	// "$3,500–$60,000" and captures the string "$3", which then fails as a
	// non-canonical price on every page carrying a priceRange.
	push(
		"JSON-LD price field",
		/"(?:price|priceRange|lowPrice|highPrice|minPrice|maxPrice)"\s*:\s*(?:"([^"]*)"|([0-9.]+))/gi,
	);
	// A stamped span is generated from the facts file, so a non-canonical value
	// in one means facts:render was skipped. check-facts.mjs proves this too;
	// keeping it here means one command answers "is every number right?".
	push("data-fact span", /<span[^>]*data-fact="[^"]*"[^>]*>([\s\S]*?)<\/span>/gi);
	return out;
}

// --- checks -----------------------------------------------------------------

const EXPECTED_RANGE = priceRange(COMPANY);
let prosePrices = 0;
let filesScanned = 0;

for (const file of htmlFiles(ROOT)) {
	const rel = path.relative(ROOT, file);
	const raw = fs.readFileSync(file, "utf8");
	const html = stripNonClaims(raw);
	filesScanned++;

	// --- 1. PHONE, everywhere ---
	for (const m of html.matchAll(PHONE)) {
		const found = m[0].trim();
		const normal = found.replace(/[^\d+]/g, "");
		const ok = [...PHONE_FORMS].some((f) => f.replace(/[^\d+]/g, "") === normal);
		if (ok) continue;
		// An <input placeholder> is a format hint, not a claim. Scoped tightly:
		// only this attribute, only on the same tag.
		const before = html.slice(Math.max(0, m.index - 260), m.index);
		if (/placeholder="[^"]*$/.test(before)) continue;
		fail(`${rel}:${lineOf(html, m.index)} — non-canonical phone "${found}" (canonical: ${COMPANY.phone})`);
	}

	// --- 5. RETIRED tokens, everywhere ---
	for (const { pattern, why } of RETIRED) {
		for (const m of html.matchAll(pattern)) {
			fail(`${rel}:${lineOf(html, m.index)} — "${m[0]}" is ${why}`);
		}
	}

	// --- 4. NEAR-MISS ranges, everywhere (including prose) ---
	// This is the rule that actually catches a repricing: a range pairing a
	// canonical endpoint with a non-canonical one ("$18,000–$45,000") is a copy
	// somebody half-updated. Ranges where NEITHER endpoint is canonical are
	// market context ("$130,000–$200,000 for an in-house hire") and are left
	// alone — that distinction is what keeps this check usable.
	for (const m of html.matchAll(RANGE)) {
		const lo = num(m[1]), hi = num(m[2]);
		const loOk = CANONICAL_ENDPOINTS.has(lo), hiOk = CANONICAL_ENDPOINTS.has(hi);
		if (CANONICAL_PRICES.has(m[0])) continue; // a known-good string, incl. the composite
		if (!loOk && !hiOk) continue;             // neither endpoint is ours — editorial
		if (loOk && hiOk) {
			// Both endpoints are ours but the pairing is not a published price —
			// e.g. "$8,500–$18,000", which reads as a band we do not sell.
			fail(
				`${rel}:${lineOf(html, m.index)} — "${m[0]}" pairs two canonical prices into ` +
				`a band we do not publish. Published: ` +
				`${COMPANY.services.filter((s) => s.priceHigh).map((s) => s.price).join(", ")}, ` +
				`composite ${EXPECTED_RANGE}.`,
			);
			continue;
		}
		fail(
			`${rel}:${lineOf(html, m.index)} — "${m[0]}" pairs a canonical price with a ` +
			`non-canonical one — a half-updated range. Published: ` +
			COMPANY.services.filter((s) => s.priceHigh).map((s) => s.price).join(", "),
		);
	}

	// --- 3. priceRange must equal the derived composite, exactly ---
	for (const m of html.matchAll(/"priceRange"\s*:\s*"([^"]*)"/g)) {
		if (m[1] !== EXPECTED_RANGE) {
			fail(
				`${rel}:${lineOf(html, m.index)} — JSON-LD priceRange is "${m[1]}", derived ` +
				`value is "${EXPECTED_RANGE}" (audit floor → sprint ceiling). This string is ` +
				`hardcoded in ~39 pages and cannot be stamped, so it is guarded instead: ` +
				`re-derive it from site-facts.json.`,
			);
		}
	}

	// --- 2. PRICES in structured price fields ---
	for (const region of factBearingRegions(html)) {
		for (const m of region.text.matchAll(MONEY)) {
			const tok = m[0];
			if (CANONICAL_PRICES.has(tok)) continue;
			// An endpoint of a canonical range is fine on its own.
			const around = region.text.slice(Math.max(0, m.index - 14), m.index + tok.length + 14);
			if ([...around.matchAll(RANGE)].some((r) => CANONICAL_PRICES.has(r[0]))) continue;
			fail(
				`${rel}:${lineOf(html, region.index)} — non-canonical price "${tok}" in a ` +
				`${region.label}. That field is a machine-readable claim about our pricing; ` +
				`use a value from site-facts.json.`,
			);
		}
	}

	// --- reported, never failed: prose prices (editorial market context) ---
	for (const m of html.matchAll(MONEY)) {
		if (!CANONICAL_PRICES.has(m[0])) prosePrices++;
	}
}

// --- report -----------------------------------------------------------------

console.log(
	`[numbers:check] ${filesScanned} page(s) scanned · ` +
	`canonical prices: ${[...CANONICAL_PRICES].join(", ")} · phone: ${COMPANY.phone}`,
);
console.log(
	`[numbers:check] ${prosePrices} non-canonical price mention(s) in body prose — ` +
	`NOT failed (editorial market context: competitor rates, ROI examples, token costs). ` +
	`Rules 1/3/4/5 still cover those regions.`,
);
if (warnings) console.log(`[numbers:check] ${warnings} warning(s)`);
if (failures) {
	console.error(`\n[numbers:check] FAILED — ${failures} problem(s). Facts live in src/data/site-facts.json.`);
	process.exit(1);
}
console.log("[numbers:check] OK — every price claim and phone number is canonical.");
