#!/usr/bin/env node
/**
 * Stamp `data-cta="<placement>"` on every internal booking CTA in committed HTML.
 *
 * WHY THIS EXISTS. `js/analytics.js` used to INFER the placement of a /book link
 * from its ancestor classes. Inference was both incomplete and wrong:
 *
 *   - 16 links matched no region at all and fired NOTHING — the /pricing/ FAQ
 *     strip, /security/, /contact/, /404.html and nine in-prose links were
 *     invisible in Plausible.
 *   - 35 of the 36 links reported as `hero` were not heroes. `.hero__cta` is a
 *     shared CTA-row wrapper, so the pre-footer `.final` band on 30 pages, two
 *     page heroes and three /work/marcus/ mid-page CTAs all reported as "hero".
 *     The one real hero was the homepage's.
 *
 * An attribute in the markup cannot drift the way an ancestor-class guess can:
 * moving a CTA into a different wrapper no longer silently relabels it.
 *
 * The inference fallback in analytics.js is KEPT (corrected) so a newly added
 * link is never silently untracked — but every link that exists today is
 * stamped, so the fallback should be dead code in practice. `npm run cta:check`
 * fails the build if an unstamped /book link appears.
 *
 * Blog chrome is NOT stamped here — it is generated by `scripts/lib/templates.mjs`,
 * which carries the same three attributes inline.
 *
 *   node scripts/stamp-cta.mjs --dry    report only
 *   node scripts/stamp-cta.mjs          write
 */
import fs from "node:fs";
import path from "node:path";
import http from "node:http";
import { ROOT, LOCAL_SCRATCH_DIRS } from "./lib/config.mjs";

const DRY = process.argv.includes("--dry");
const PORT = 8179;

/**
 * Walk the committed HTML rather than STATIC_ROUTES — the two are not the same
 * set, and the difference is exactly where a CTA hides. /book/thanks/ is a
 * NOINDEX route, so it is absent from STATIC_ROUTES; it carries four booking
 * links, and a STATIC_ROUTES-driven stamper left every one of them unstamped
 * while reporting success. `blog/` is skipped because it is generated from
 * templates.mjs, which carries the attributes inline.
 */
const ROUTES = (function () {
	const out = [];
	(function walk(d) {
		for (const e of fs.readdirSync(d, { withFileTypes: true })) {
			if (e.name === "node_modules" || e.name.startsWith(".") || e.name === "emails") continue;
			if (d === ROOT && (LOCAL_SCRATCH_DIRS.has(e.name) || e.name === "blog")) continue;
			const f = path.join(d, e.name);
			if (e.isDirectory()) walk(f);
			else if (e.name.endsWith(".html")) {
				const rel = "/" + path.relative(ROOT, f).split(path.sep).join("/");
				out.push(rel.endsWith("/index.html") ? rel.slice(0, -"index.html".length) : rel);
			}
		}
	})(ROOT);
	return out.sort();
})();

/**
 * Placement rules, first match wins. Evaluated in the browser against each
 * anchor. Ordered chrome → page-level bands → in-prose, so the most specific
 * container answers first.
 */
const RULES = `[
  [".ticker",                       "ticker"],
  ["header.nav",                    "nav"],
  [".foot",                         "footer"],
  [".thankshero__crumb, .bookhero__crumb, .sechero__crumb, .legal__crumb, .crumb", "breadcrumb"],
  ["section.final",                 "final-cta"],
  [".paths",                        "door"],
  [".calcband",                     "calculator"],
  [".faq-strip",                    "faq-strip"],
  [".contact-cta",                  "contact-cta"],
  [".reviewer",                     "security-reviewer"],
  [".nf__links",                    "not-found"],
  [".legal",                        "legal"],
  [".rail",                         "rail"],
  [".bookhero",                     "page-hero"],
  [".pagehero, .sechero, .cr-hero", "page-hero"],
  ["section.hero",                  "hero"],
  [".svc__item",                    "pricing-row"],
  [".builds__note, .buildstrip",    "build-strip"],
  ["p, li, dd",                     "prose"]
]`;

function serve() {
	const types = { html: "text/html", css: "text/css", js: "text/javascript", mjs: "text/javascript", json: "application/json", png: "image/png", svg: "image/svg+xml", ico: "image/x-icon", xml: "application/xml", txt: "text/plain" };
	const server = http.createServer((req, res) => {
		let p = decodeURIComponent(new URL(req.url, "http://x").pathname);
		let file = path.join(ROOT, p);
		if (p.endsWith("/")) file = path.join(file, "index.html");
		try {
			const data = fs.readFileSync(file);
			res.writeHead(200, { "Content-Type": types[path.extname(file).slice(1)] || "application/octet-stream" });
			res.end(data);
		} catch { res.writeHead(404); res.end("not found"); }
	});
	return new Promise((r) => server.listen(PORT, "127.0.0.1", () => r(server)));
}

async function loadPlaywright() {
	for (const c of [process.env.PLAYWRIGHT_PATH, "playwright"].filter(Boolean)) {
		try { return await import(c.startsWith("/") ? path.join(c, "index.mjs") : c); } catch { /* next */ }
	}
	console.error("Playwright not found. `npm i -D playwright` or set PLAYWRIGHT_PATH.");
	process.exit(2);
}

const routeToFile = (r) => path.join(ROOT, r.endsWith("/") ? path.join(r, "index.html") : r);

/**
 * Every /book anchor's OPEN TAG in source order. The DOM order playwright
 * reports matches source order because nothing on the site injects a booking
 * link at runtime (verified: js/nav.js only rewrites the quarter span).
 */
const OPEN_TAG = /<a\b[^>]*\bhref="\/book[^"]*"[^>]*>/gi;

const { chromium } = await loadPlaywright();
const server = await serve();
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });

let stamped = 0, already = 0, unresolved = 0, filesChanged = 0;
const tally = {};

for (const route of ROUTES) {
	const file = routeToFile(route);
	if (!fs.existsSync(file)) continue;

	await page.goto(`http://127.0.0.1:${PORT}${route}`, { waitUntil: "domcontentloaded" });
	const placements = await page.evaluate((rulesSrc) => {
		const rules = JSON.parse(rulesSrc);
		return [...document.querySelectorAll("a[href]")]
			.filter((a) => (a.getAttribute("href") || "").startsWith("/book"))
			.map((a) => {
				if (a.hasAttribute("data-cta")) return { has: a.getAttribute("data-cta") };
				for (const [sel, name] of rules) if (a.closest(sel)) return { name };
				return { name: null };
			});
	}, RULES);

	let src = fs.readFileSync(file, "utf8");
	const tags = src.match(OPEN_TAG) || [];
	if (tags.length !== placements.length) {
		console.error(`  !! ${route}: ${tags.length} source tags vs ${placements.length} DOM anchors — skipped`);
		continue;
	}

	let i = 0, changed = false;
	src = src.replace(OPEN_TAG, (tag) => {
		const p = placements[i++];
		if (p.has) { already++; tally[p.has] = (tally[p.has] || 0) + 1; return tag; }
		if (!p.name) { unresolved++; console.error(`  ?? ${route}: no rule matched — ${tag.slice(0, 90)}`); return tag; }
		tally[p.name] = (tally[p.name] || 0) + 1;
		stamped++; changed = true;
		// Insert immediately after `<a` so the attribute reads before href.
		return tag.replace(/^<a\b/i, `<a data-cta="${p.name}"`);
	});

	if (changed) {
		filesChanged++;
		if (!DRY) fs.writeFileSync(file, src);
	}
}

await browser.close();
server.close();

console.log(`\n${DRY ? "DRY RUN — " : ""}data-cta stamping`);
console.log(`  files ${DRY ? "would change" : "changed"}: ${filesChanged}`);
console.log(`  stamped: ${stamped}   already had one: ${already}   UNRESOLVED: ${unresolved}`);
console.log("\n  placement tally:");
for (const [k, v] of Object.entries(tally).sort((a, b) => b[1] - a[1])) {
	console.log(`    ${String(v).padStart(3)}×  ${k}`);
}
if (unresolved) { console.error("\nFAIL: a booking CTA matched no placement rule."); process.exit(1); }
